import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

/// The [History] class holds the list of items generated by the user.
class History extends ChangeNotifier {
  List<WordPair> _historyItems = [WordPair.random()];
  GlobalKey? listKey;

  List<WordPair> get items => _historyItems;
  WordPair get current => _historyItems[0];

  void getNext() {
    var animatedList = listKey?.currentState as AnimatedListState?;
    animatedList?.insertItem(0);
    _historyItems.insert(0, WordPair.random());
    notifyListeners();
  }
}
